### Prepare the dataset

In [1]:
import pandas as pd
import numpy as np
# import seaborn as sns

In [2]:
from sklearn import datasets 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split  
from sklearn import preprocessing

In [163]:
# Sample_Dataset.csv is the original dataset
# Sample_Dataset2.csv is adjusted dataset with manually adjusted values to create prediction errors

In [102]:
df = pd.read_csv('SensorData.csv')

In [121]:
df = pd.read_csv('GeneratedData.csv')

In [47]:
df

light_intensity  temperature  humidity  label
0                   90           23        13      2
1                  734           26        95      0
2                  122           22        62      2
3                   60           21        80      2
4                  660           26        92      0
...                ...          ...       ...    ...
11995              441           32        83      1
11996              427           30        87      1
11997              389           31        82      1
11998              583           31        85      1
11999              528           30        82      1

[12000 rows x 4 columns]

In [7]:
df['light_intensity'].mean()

368.3073394495413

In [8]:
df.values

array([[345.  ,  29.04,  82.2 ,   1.  ],
       [101.  ,  22.55,  73.  ,   2.  ],
       [ 76.  ,  22.79,  78.7 ,   2.  ],
       ...,
       [ 42.  ,  22.65,  68.3 ,   2.  ],
       [386.  ,  28.56,  83.3 ,   1.  ],
       [249.  ,  29.62,  88.  ,   1.  ]])

#### Generate data

In [24]:
df0l = pd.DataFrame(np.random.randint(320, 400, size=(1000, 1)), columns = ['light_intensity'])

In [25]:
df0t = pd.DataFrame(np.random.randint(26, 28, size=(1000, 1)), columns = ['temperature'])

In [26]:
df0h = pd.DataFrame(np.random.randint(93, 100, size=(1000, 1)), columns = ['humidity'])

In [27]:
df00 = pd.concat([df0l, df0t, df0h], axis = 1)

In [28]:
df00['label'] = 0

In [901]:
df00

light_intensity  temperature  humidity  label
0                354           27        96      0
1                345           26        98      0
2                376           27        93      0
3                369           27        99      0
4                386           27        96      0
5                342           27        93      0
6                354           27        98      0
7                376           26        98      0
8                321           27        94      0
9                371           27        94      0
10               397           26        93      0
11               390           26        99      0
12               353           27        98      0
13               371           27        93      0
14               364           27        95      0
15               391           27        95      0
16               371           26        95      0
17               362           27        94      0
18               341           26        96      0
19               354           26        99      0
20               377           27        93      0
21               338           27        94      0
22               326           26        95      0
23               324           27        94      0
24               341           27        93      0
25               327           27        97      0
26               320           26        98      0
27               329           26        98      0
28               322           26        93      0
29               393           27        97      0
..               ...          ...       ...    ...
970              367           27        94      0
971              374           27        96      0
972              381           27        94      0
973              324           26        93      0
974              370           26        96      0
975              353           27        98      0
976              371           26        96      0
977              355           26        93      0
978              324           26        93      0
979              350           26        96      0
980              365           27        98      0
981              341           27        95      0
982              392           26        94      0
983              397           27        96      0
984              356           27        98      0
985              351           26        96      0
986              360           27        99      0
987              358           27        93      0
988              366           26        96      0
989              393           27        96      0
990              379           27        94      0
991              384           26        96      0
992              365           27        96      0
993              395           26        99      0
994              390           26        93      0
995              396           26        97      0
996              375           26        98      0
997              385           27        99      0
998              370           26        93      0
999              325           26        94      0

[1000 rows x 4 columns]

In [29]:
df1l = pd.DataFrame(np.random.randint(240, 319, size=(1000, 1)), columns = ['light_intensity'])

In [30]:
df1t = pd.DataFrame(np.random.randint(29, 32, size=(1000, 1)), columns = ['temperature'])

In [31]:
df1h = pd.DataFrame(np.random.randint(88, 92, size=(1000, 1)), columns = ['humidity'])

In [32]:
df11 = pd.concat([df1l, df1t, df1h], axis = 1)

In [33]:
df11['label'] = 1

In [907]:
df11

light_intensity  temperature  humidity  label
0                314           29        89      1
1                278           29        91      1
2                311           31        90      1
3                312           29        90      1
4                247           30        88      1
5                265           31        89      1
6                317           31        91      1
7                262           29        91      1
8                297           29        89      1
9                264           31        88      1
10               283           29        91      1
11               311           31        90      1
12               293           29        89      1
13               308           30        89      1
14               247           31        89      1
15               242           31        89      1
16               268           31        91      1
17               305           29        90      1
18               268           31        91      1
19               266           30        90      1
20               285           30        89      1
21               255           29        91      1
22               284           30        88      1
23               303           29        90      1
24               260           31        90      1
25               307           29        88      1
26               299           29        88      1
27               243           30        89      1
28               307           30        90      1
29               283           30        88      1
..               ...          ...       ...    ...
970              251           30        90      1
971              271           31        88      1
972              258           30        88      1
973              294           30        88      1
974              317           31        89      1
975              279           29        90      1
976              316           31        89      1
977              261           30        89      1
978              266           30        88      1
979              258           30        90      1
980              282           31        91      1
981              252           31        90      1
982              270           29        89      1
983              295           29        89      1
984              292           29        88      1
985              257           31        91      1
986              255           29        90      1
987              259           31        89      1
988              307           31        89      1
989              297           29        91      1
990              308           29        88      1
991              263           29        88      1
992              272           31        90      1
993              300           30        88      1
994              266           30        91      1
995              303           31        89      1
996              271           29        88      1
997              273           31        90      1
998              290           29        90      1
999              248           30        90      1

[1000 rows x 4 columns]

In [908]:
df2l = pd.DataFrame(np.random.randint(100, 239, size=(1000, 1)), columns = ['light_intensity'])

In [909]:
df2t = pd.DataFrame(np.random.randint(20, 25, size=(1000, 1)), columns = ['temperature'])

In [910]:
df2h = pd.DataFrame(np.random.randint(60, 87, size=(1000, 1)), columns = ['humidity'])

In [911]:
df22 = pd.concat([df2l, df2t, df2h], axis = 1)

In [912]:
df22['label'] = 2

In [948]:
df22

light_intensity  temperature  humidity  label
0                166           23        74      2
1                122           23        72      2
2                111           24        68      2
3                209           22        69      2
4                166           23        72      2
5                144           20        65      2
6                229           23        70      2
7                204           23        66      2
8                172           23        78      2
9                232           21        80      2
10               212           21        60      2
11               133           22        69      2
12               204           22        70      2
13               216           21        70      2
14               226           23        78      2
15               109           24        70      2
16               189           21        76      2
17               116           23        71      2
18               182           20        69      2
19               198           23        60      2
20               203           23        81      2
21               208           23        76      2
22               224           24        78      2
23               223           24        83      2
24               177           23        62      2
25               227           23        63      2
26               168           20        75      2
27               219           24        82      2
28               228           22        70      2
29               225           20        80      2
..               ...          ...       ...    ...
970              133           23        73      2
971              180           20        79      2
972              109           20        69      2
973              189           22        84      2
974              123           22        83      2
975              159           20        75      2
976              104           20        72      2
977              116           21        81      2
978              180           22        62      2
979              223           22        74      2
980              106           23        77      2
981              103           22        61      2
982              135           20        67      2
983              153           23        62      2
984              134           22        79      2
985              214           22        78      2
986              119           20        72      2
987              180           20        85      2
988              128           24        65      2
989              177           24        65      2
990              141           20        69      2
991              154           23        75      2
992              158           20        68      2
993              116           22        68      2
994              101           22        77      2
995              146           23        79      2
996              167           24        68      2
997              161           23        66      2
998              107           24        66      2
999              174           21        82      2

[1000 rows x 4 columns]

In [914]:
df = pd.concat([df00, df11, df22], axis = 0)

In [34]:
df = pd.concat([df00, df11], axis = 0)

In [109]:
# dftrain = df

In [37]:
df

light_intensity  temperature  humidity  label
0                 359           27        94      0
1                 240           31        89      1
2                 361           27        94      0
3                 290           31        88      1
4                 391           27        99      0
...               ...          ...       ...    ...
1995              282           29        91      1
1996              318           30        91      1
1997              280           29        88      1
1998              294           30        89      1
1999              313           31        91      1

[2000 rows x 4 columns]

In [165]:
df = df.sample(frac=1).reset_index(drop=True)

#### Train Test Split

In [122]:
y = df.loc[ : , 'label']
x = df.drop(['label'], axis = 1)

In [123]:
x_array = x.values
y_array = y.values.astype(int)

In [70]:
x_array

array([[345.  ,  29.04,  82.2 ],
       [101.  ,  22.55,  73.  ],
       [ 76.  ,  22.79,  78.7 ],
       ...,
       [ 42.  ,  22.65,  68.3 ],
       [386.  ,  28.56,  83.3 ],
       [249.  ,  29.62,  88.  ]])

In [71]:
y_array

array([1, 2, 2, 1, 0, 2, 0, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 0,
       2, 1, 0, 1, 1, 0, 1, 1, 2, 2, 2, 0, 1, 1, 0, 2, 1, 2, 1, 2, 0, 2,
       1, 1, 2, 2, 2, 0, 1, 1, 0, 1, 0, 2, 2, 2, 0, 0, 1, 1, 2, 1, 1, 1,
       0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 2, 1, 2, 1, 2, 0, 0, 0,
       0, 0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 1,
       2, 1, 2, 1, 0, 1, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 1,
       2, 1, 0, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 0, 1, 0, 2, 1, 1, 2,
       0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0,
       0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 1, 0, 0, 0, 0, 2, 1, 1, 2, 2, 2, 1,
       1, 2, 0, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 2,
       2, 0, 1, 0, 1, 2, 0, 1, 2, 1, 0, 0, 0, 1, 2, 0, 2, 0, 2, 0, 1, 2,
       0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       2, 0, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,

In [112]:
x_array.dtype

dtype('int64')

In [113]:
y_array.dtype

dtype('int32')

In [114]:
x_array.shape

(10000L, 3L)

In [115]:
y_array.shape

(10000L,)

In [124]:
x_train, x_test, y_train, y_test = train_test_split(x_array, y_array, test_size=0.2, random_state=42)

In [53]:
type(x_test)

numpy.ndarray

In [73]:
print (x_train.shape, y_train.shape)

(697, 3) (697,)


In [74]:
print (x_test.shape, y_test.shape)

(175, 3) (175,)


#### Scaling the array

##### Method 1

In [120]:
x_scaled = preprocessing.scale(x_train)

In [121]:
x_scaled

array([[-0.0554689 , -0.38302987,  0.56418098],
       [ 0.9994669 ,  0.08276781,  0.8339719 ],
       [ 0.76399015,  0.16040076,  0.69907644],
       ...,
       [-0.38513634,  2.17885738, -2.33607137],
       [-0.4887461 ,  1.94595854, -0.98711679],
       [ 1.6493827 ,  0.08276781,  0.8339719 ]])

In [122]:
x_scaled.mean(axis=0)

array([-7.75252878e-17, -8.88178420e-18, -2.77714359e-17])

In [123]:
x_scaled.std(axis=0)

array([1., 1., 1.])

##### Method 2

In [125]:
scaler = preprocessing.StandardScaler().fit(x_train)

In [128]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [126]:
scaler.mean_

array([399.30510417,  25.99125   ,  73.26354167])

In [127]:
scaler.scale_

array([259.5948613 ,   3.87716693,  27.53831278])

#### Generate sensor data

In [173]:
# Optimal [light, temp, humidity]
sensorReadings = [770, 27, 97]

In [205]:
# Sub Optimal [light, temp, humidity]
sensorReadings = [290, 30, 90]

In [212]:
# Bad [light, temp, humidity]
sensorReadings = [200, 25, 85]

In [206]:
infer = np.array([sensorReadings])
infer = scaler.transform(infer)

In [207]:
infer

array([[-0.26130655,  1.63426745,  0.64535788]])

#### Test with unseen labeled data

In [129]:
dftest = pd.read_csv('CleanedData.csv')

In [130]:
ytest = dftest.loc[ : , 'label']
xtest = dftest.drop(['label'], axis = 1)

In [131]:
x_test = xtest.values
y_test = ytest.values.astype(int)

In [132]:
x_test = scaler.transform(x_test)

### Naive Bayes

In [13]:
from sklearn.naive_bayes import GaussianNB 

In [14]:
gnb = GaussianNB().fit(x_train, y_train) 
gnb_predictions = gnb.predict(x_test) 

In [15]:
gnb_proba = gnb.predict_proba(x_test) 
gnb_proba

array([[6.71027604e-075, 1.59751108e-034, 1.00000000e+000],
       [1.00000000e+000, 6.92992532e-043, 3.54825636e-063],
       [1.00000000e+000, 9.85966930e-044, 1.74704024e-069],
       [2.90853044e-043, 1.00000000e+000, 7.25657345e-068],
       [2.43747196e-123, 3.86835056e-061, 1.00000000e+000],
       [7.94430140e-076, 1.95284449e-037, 1.00000000e+000],
       [1.00166727e-079, 3.50688183e-036, 1.00000000e+000],
       [1.00000000e+000, 4.78476401e-039, 3.42370217e-057],
       [3.36343814e-023, 1.00000000e+000, 6.65137077e-063],
       [1.00000000e+000, 6.60199146e-045, 1.22488381e-070],
       [1.00000000e+000, 6.85532656e-030, 1.24576464e-082],
       [1.00000000e+000, 3.16614633e-035, 4.30175270e-060],
       [3.41875869e-102, 3.72568358e-050, 1.00000000e+000],
       [2.40239187e-047, 1.00000000e+000, 1.50645729e-068],
       [6.81696266e-046, 1.00000000e+000, 1.99691652e-076],
       [1.00000000e+000, 3.70961152e-041, 3.63232222e-062],
       [1.00000000e+000, 3.39390243e-034

In [17]:
accuracy = gnb.score(x_test, y_test) 
print (accuracy) 

1.0


In [18]:
cmnb = confusion_matrix(y_test, gnb_predictions)

In [20]:
print(cmnb)

[[57  0  0]
 [ 0 58  0]
 [ 0  0 60]]


In [55]:
gnb_predictions = gnb.predict(infer)
gnb_predictions.item(0)

0

In [56]:
gnb_proba = gnb.predict_proba(infer) 
gnb_proba

array([[1.00000000e+00, 3.50752364e-30, 5.04562632e-93]])

In [25]:
%%timeit
gnb_predictions = gnb.predict(infer)
gnb_predictions.item(0)

10000 loops, best of 3: 88.9 µs per loop


### SVM

In [23]:
from sklearn.svm import SVC 

In [133]:
svm_model_linear = SVC(kernel = 'linear', C = 1, probability=True).fit(x_train, y_train) 

In [134]:
svm_predictions = svm_model_linear.predict(x_test) 

In [135]:
svm_proba = svm_model_linear.predict_proba(x_test) 
svm_proba

array([[4.11919956e-11, 9.99996779e-01, 3.22126237e-06],
       [4.53635602e-11, 9.99996635e-01, 3.36519142e-06],
       [4.03702848e-11, 9.99996751e-01, 3.24903217e-06],
       [1.22630455e-10, 9.99993531e-01, 6.46856457e-06],
       [7.27018075e-11, 9.99995603e-01, 4.39679162e-06],
       [7.40554683e-11, 9.99995029e-01, 4.97111108e-06],
       [1.17121398e-10, 9.99993830e-01, 6.17034487e-06],
       [1.28904889e-10, 9.99993316e-01, 6.68395091e-06],
       [6.65366005e-11, 9.99992778e-01, 7.22227206e-06],
       [9.50228545e-11, 9.99993473e-01, 6.52695609e-06],
       [5.27886611e-11, 9.99996164e-01, 3.83613714e-06],
       [3.57041568e-11, 9.99996968e-01, 3.03163707e-06],
       [4.07448086e-11, 9.99996435e-01, 3.56500636e-06],
       [6.39514494e-11, 9.99995592e-01, 4.40798667e-06],
       [9.99971061e-01, 1.04584981e-07, 2.88346652e-05],
       [9.99914516e-01, 2.43529039e-06, 8.30490715e-05],
       [9.99818697e-01, 5.67147689e-06, 1.75631788e-04],
       [9.99792796e-01, 6.05736

In [136]:
accuracy = svm_model_linear.score(x_test, y_test) 

In [137]:
accuracy

1.0

In [138]:
cmsvm = confusion_matrix(y_test, svm_predictions)

In [139]:
print(cmsvm)

[[91  0  0]
 [ 0 14  0]
 [ 0  0 21]]


In [182]:
svm_predictions = svm_model_linear.predict(infer) 
svm_predictions.item(0)

0

In [208]:
svm_proba = svm_model_linear.predict_proba(infer) 
svm_proba

array([[2.85474430e-03, 9.96644578e-01, 5.00678157e-04]])

In [209]:
prob_list = svm_proba.tolist()

In [197]:
prob_list

[[0.9927049297408137, 0.006884833156878635, 0.0004102371023075967]]

In [198]:
max(prob_list[0])

0.9927049297408137

In [210]:
inferred_class = prob_list[0].index(max(prob_list[0]))

In [211]:
inferred_class

1

In [212]:
pred_prob = round(svm_proba[0, inferred_class], 2) *100

In [213]:
pred_prob

100.0

In [214]:
pred_prob0 = svm_proba[0, 0]
pred_prob1 = svm_proba[0, 1]
pred_prob2 = svm_proba[0, 2]

print('prob/prob1', pred_prob0)
print('prob/prob2', pred_prob1)
print('prob/prob3', pred_prob2)

prob/prob1 0.002854744302689357
prob/prob2 0.9966445775401056
prob/prob3 0.0005006781572050141


In [216]:
label_dict = {0:'Perfect!', 1:"Sub optimal", 2:"Bad"}
label = label_dict[inferred_class]

print (label)

Sub optimal


In [35]:
%%timeit
svm_predictions = svm_model_linear.predict(infer) 
svm_predictions.item(0)

10000 loops, best of 3: 37.6 µs per loop


#### To confirm svm_predict returns max.svm_prob 

In [102]:
svm_model_linear = SVC(kernel = 'linear', C = 1, probability=True).fit(x_train, y_train) 

In [125]:
svm_predictions = svm_model_linear.predict(x_test) 

In [137]:
svm_predictions = svm_model_linear.predict(infer) 

In [138]:
svm_predictions

array([0])

In [139]:
svm_predictions.item(0)

0

In [127]:
len(svm_predictions)

400

In [112]:
svm_proba = svm_model_linear.predict_proba(x_test) 

In [113]:
svm_proba

array([[2.90101163e-03, 9.97098988e-01],
       [9.81618782e-01, 1.83812179e-02],
       [9.99996276e-01, 3.72418454e-06],
       [1.64696594e-05, 9.99983530e-01],
       [2.04119943e-07, 9.99999796e-01],
       [2.46085195e-06, 9.99997539e-01],
       [9.99756498e-01, 2.43501902e-04],
       [9.99992091e-01, 7.90937267e-06],
       [1.24237594e-02, 9.87576241e-01],
       [9.99874656e-01, 1.25343914e-04],
       [3.98759244e-08, 9.99999960e-01],
       [1.92968659e-07, 9.99999807e-01],
       [9.99505251e-01, 4.94749147e-04],
       [1.22526724e-02, 9.87747328e-01],
       [3.11137053e-03, 9.96888629e-01],
       [1.99949894e-11, 1.00000000e+00],
       [6.19920772e-10, 9.99999999e-01],
       [9.99483962e-01, 5.16037970e-04],
       [9.99859452e-01, 1.40548239e-04],
       [9.99941679e-01, 5.83209578e-05],
       [9.99969915e-01, 3.00854527e-05],
       [3.70292199e-09, 9.99999996e-01],
       [9.99991979e-01, 8.02122913e-06],
       [3.35622947e-09, 9.99999997e-01],
       [9.275598

In [114]:
len(svm_proba)

400

In [115]:
prob_list = svm_proba.tolist()

In [116]:
prob_list

[[0.0029010116263622552, 0.9970989883736378],
 [0.9816187820960834, 0.018381217903916485],
 [0.9999962758154549, 3.724184544974663e-06],
 [1.646965937142761e-05, 0.9999835303406286],
 [2.0411994269447517e-07, 0.9999997958800574],
 [2.460851945943725e-06, 0.9999975391480541],
 [0.9997564980979206, 0.0002435019020794045],
 [0.9999920906273291, 7.909372670946391e-06],
 [0.012423759365063588, 0.9875762406349363],
 [0.9998746560855216, 0.00012534391447831491],
 [3.987592435601511e-08, 0.9999999601240755],
 [1.9296865862959294e-07, 0.9999998070313413],
 [0.999505250853216, 0.0004947491467841428],
 [0.012252672394509164, 0.9877473276054908],
 [0.0031113705319022497, 0.9968886294680978],
 [1.999498941493762e-11, 0.999999999980005],
 [6.199207724610091e-10, 0.9999999993800791],
 [0.9994839620301743, 0.0005160379698257846],
 [0.9998594517605087, 0.00014054823949139573],
 [0.9999416790421934, 5.8320957806550195e-05],
 [0.9999699145472936, 3.008545270643715e-05],
 [3.702921992781936e-09, 0.9999999

In [117]:
prob_list[0]

[0.0029010116263622552, 0.9970989883736378]

In [118]:
max(prob_list[1])

0.9816187820960834

In [119]:
prob_list[1].index(max(prob_list[1]))

0

In [120]:
prob_list = []
for i in prob_pred:
    prob_list.append(i.index(max(i)))

In [121]:
prob_list

[1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,


In [122]:
len(prob_list)

400

In [128]:
prob_list == svm_predictions.tolist()

True

### Decision Tree

In [36]:
from sklearn.tree import DecisionTreeClassifier 

In [37]:
dtree_model = DecisionTreeClassifier(max_depth = 3).fit(x_train, y_train) 
dtree_predictions = dtree_model.predict(x_test) 

In [38]:
dtree_proba = dtree_model.predict_proba(x_test) 
dtree_proba

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0

In [39]:
cmdt = confusion_matrix(y_test, dtree_predictions) 

In [40]:
cmdt

array([[85,  0,  0],
       [ 0, 91,  0],
       [ 0,  0, 86]], dtype=int64)

In [59]:
dtree_predictions = dtree_model.predict(infer)
dtree_predictions.item(0)

0

In [60]:
dtree_proba = dtree_model.predict_proba(infer) 
dtree_proba

array([[1., 0., 0.]])

In [42]:
%%timeit
dtree_predictions = dtree_model.predict(infer)
dtree_predictions.item(0)

10000 loops, best of 3: 30.4 µs per loop


### K-Nearest Neighbours

In [43]:
from sklearn.neighbors import KNeighborsClassifier 

In [44]:
knn = KNeighborsClassifier(n_neighbors = 7).fit(x_train, y_train) 

In [45]:
knn_proba = knn.predict_proba(x_test) 
knn_proba

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0

In [46]:
accuracy = knn.score(x_test, y_test) 
print accuracy

1.0


In [47]:
knn_predictions = knn.predict(x_test)  
cmknn = confusion_matrix(y_test, knn_predictions) 

In [48]:
cmknn

array([[85,  0,  0],
       [ 0, 91,  0],
       [ 0,  0, 86]], dtype=int64)

In [61]:
knn_predictions = knn.predict(infer)  
knn_predictions.item(0)

0

In [62]:
knn_proba = knn.predict_proba(infer) 
knn_proba

array([[1., 0., 0.]])

In [50]:
%%timeit
knn_predictions = knn.predict(infer)  
knn_predictions.item(0)

1000 loops, best of 3: 377 µs per loop


### Multi Layer Perceptron

In [63]:
from sklearn.neural_network import MLPClassifier

In [64]:
mlp = MLPClassifier(hidden_layer_sizes=(10,), activation='logistic', max_iter=100, alpha=1e-4,
                    solver='sgd', verbose=10, random_state=1,
                    learning_rate_init=.1)

mlp.fit(x_train, y_train)

print("\n Training set score: %f" % mlp.score(x_train, y_train))

Iteration 1, loss = 1.13787980
Iteration 2, loss = 1.01142875
Iteration 3, loss = 0.90505762
Iteration 4, loss = 0.71046574
Iteration 5, loss = 0.54927603
Iteration 6, loss = 0.37013482
Iteration 7, loss = 0.23252369
Iteration 8, loss = 0.14912053
Iteration 9, loss = 0.09875676
Iteration 10, loss = 0.06805898
Iteration 11, loss = 0.04972234
Iteration 12, loss = 0.03830662
Iteration 13, loss = 0.03094339
Iteration 14, loss = 0.02602109
Iteration 15, loss = 0.02248152
Iteration 16, loss = 0.01985690
Iteration 17, loss = 0.01789049
Iteration 18, loss = 0.01638394
Iteration 19, loss = 0.01517660
Iteration 20, loss = 0.01417508
Iteration 21, loss = 0.01332481
Iteration 22, loss = 0.01258639
Iteration 23, loss = 0.01195778
Iteration 24, loss = 0.01140376
Iteration 25, loss = 0.01090959
Iteration 26, loss = 0.01045418
Iteration 27, loss = 0.01004075
Iteration 28, loss = 0.00965859
Iteration 29, loss = 0.00931232
Iteration 30, loss = 0.00898621
Iteration 31, loss = 0.00867715
Iteration 32, los

In [65]:
mlp_predictions = mlp.predict(x_test) 

In [66]:
mlp_proba = mlp.predict_proba(x_test)
mlp_proba

array([[2.61421455e-04, 2.67016074e-03, 9.97068418e-01],
       [9.98419131e-01, 1.05821600e-03, 5.22653319e-04],
       [9.98140423e-01, 1.05815161e-03, 8.01425047e-04],
       [8.42678716e-04, 9.97228135e-01, 1.92918593e-03],
       [7.67056432e-05, 1.56257445e-03, 9.98360720e-01],
       [4.91754931e-04, 2.12400683e-03, 9.97384238e-01],
       [3.84017537e-04, 2.66679085e-03, 9.96949192e-01],
       [9.98008650e-01, 1.23166620e-03, 7.59683727e-04],
       [8.87078345e-03, 9.89461814e-01, 1.66740279e-03],
       [9.98445940e-01, 1.02457363e-03, 5.29486074e-04],
       [9.91523094e-01, 8.00670399e-03, 4.70201956e-04],
       [9.97343873e-01, 1.93225680e-03, 7.23870439e-04],
       [1.17396289e-04, 1.49933115e-03, 9.98383273e-01],
       [6.43982631e-04, 9.97374410e-01, 1.98160759e-03],
       [9.82898941e-04, 9.98177865e-01, 8.39236145e-04],
       [9.98292909e-01, 1.34369881e-03, 3.63392477e-04],
       [9.96048188e-01, 3.40590503e-03, 5.45906741e-04],
       [1.14900705e-03, 2.63334

In [67]:
accuracy = mlp.score(x_test, y_test) 
print accuracy 

1.0


In [68]:
cmmlp = confusion_matrix(y_test, mlp_predictions)

In [69]:
cmmlp

array([[85,  0,  0],
       [ 0, 91,  0],
       [ 0,  0, 86]], dtype=int64)

In [71]:
mlp_predictions = mlp.predict(infer)
mlp_predictions.item(0)

0

In [73]:
mlp_proba = mlp.predict_proba(infer)
mlp_proba

array([[9.80028000e-01, 1.97281305e-02, 2.43869724e-04]])

In [70]:
%%timeit
mlp_predictions = mlp.predict(infer)
mlp_predictions.item(0)

The slowest run took 88.45 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 57.4 µs per loop
